-- Cada envio feito pelo garçom gera um lançamento
create table public.lancamentos (
  id bigint generated by default as identity primary key,

  comanda_id bigint not null
    references public.comandas(id),

  lancado_por bigint not null
    references public.garcons(id),

  criado_em timestamptz not null default now()
);

-- Cada item pertence a um lançamento
alter table public.itens_pedido
add column lancamento_id bigint
references public.lancamentos(id);

-- Define para onde o produto deve ser enviado
alter table public.produtos
add column setor text not null default 'cozinha';

-- Aceitamos inicialmente apenas cozinha ou bar
alter table public.produtos
add constraint produtos_setor_check
check (setor in ('cozinha', 'bar'));