create table public.pagamentos (
  id bigint generated by default as identity primary key,

  comanda_id bigint not null
    references public.comandas(id),

  valor numeric(10,2) not null
    check (valor > 0),

  forma text not null
    check (
      forma in (
        'dinheiro',
        'pix',
        'credito',
        'debito'
      )
    ),

  criado_em timestamptz not null default now()
);

alter table public.comandas
add column if not exists desconto numeric(10,2)
not null default 0;

alter table public.comandas
add constraint comandas_desconto_check
check (desconto >= 0);

alter table public.comandas
add column if not exists tipo_fechamento text;

alter table public.comandas
add constraint comandas_tipo_fechamento_check
check (
  tipo_fechamento is null
  or tipo_fechamento in (
    'pago',
    'fiado',
    'cortesia'
  )
);